/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#00685f",
        "on-primary": "#ffffff",
        "primary-container": "#008378",
        "on-primary-container": "#f4fffc",
        "primary-fixed": "#89f5e7",
        "primary-fixed-dim": "#6bd8cb",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        "inverse-primary": "#6bd8cb",
        "surface-tint": "#006a61",
        "secondary": "#575e70",
        "on-secondary": "#ffffff",
        "secondary-container": "#d9dff5",
        "on-secondary-container": "#5c6274",
        "secondary-fixed": "#dce2f7",
        "secondary-fixed-dim": "#c0c6db",
        "on-secondary-fixed": "#141b2b",
        "on-secondary-fixed-variant": "#404758",
        "tertiary": "#924628",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b05e3d",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#ffb59a",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-fixed-variant": "#773215",
        "surface": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3d4947",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "surface-variant": "#e1e3e4",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "outline": "#6d7a77",
        "outline-variant": "#bcc9c6",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "container_max": "1200px",
        "page_margin": "32px",
        "section_gap": "64px",
        "component_gap": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
};
